#!/usr/bin/env php
<?php

use Yasinashourian\WebServer\webserver\Request;
use Yasinashourian\WebServer\webserver\Response;
use Yasinashourian\WebServer\webserver\Server;

require_once __DIR__. DIRECTORY_SEPARATOR . "vendor/autoload.php";


/*---------------------------------------------------------------------------------------
 | If the port is entered, its value is taken into account, otherwise it is 80 by default
 |---------------------------------------------------------------------------------------
*/

array_shift($argv);

$port = empty($argv) ? 80 : array_shift($argv);

/*--------------------------------------
 |  create new server
 | --------------------------------------
*/
try {

    $server = new Server('127.0.0.1', $port);

} catch (Exception $e) {

    throw new Exception($e->getMessage());
}


/* -------------------------------------
 |  start listening
 |-------------------------------------
*/
try {
    $server->listen(function (Request $request) {

        /*--------------------------------------------
         | print information that we received the request
         | ----------------------------------------------
        */
        echo $request->method() . ' ' . $request->uri() . "\n";

        /*----------------------------------------------------
         | return a response containing the request information
         |------------------------------------------------------
         */
        return new Response( '<pre>'.print_r( $request, true ).'</pre>' );
    });
} catch (Exception $e) {

    throw new Exception($e->getMessage());
}